### ISSUE TITLE
Scroll back to top of expandable position

### ISSUE THREAD

**Issue by lifenautjoe** [aryzhov/flutter-expandable#14]
When collapsing, the scroll doesnt go back to the top of the item.

![ezgif-4-2ded4e7d9729](https://user-images.githubusercontent.com/12737509/59266942-3919bc80-8c49-11e9-8c71-8b09c6dd1901.gif)

**Comment by aryzhov** [comment]
Expandable is currently not aware of the scroll controller. I'll keep this one open. Feel free to propose a solution.

**Comment by aryzhov** [comment]
I just released version 3.0.0. It contains a solution for this issue. In order to implement scrolling back, wrap your widget with a new widget called `ScrollOnExpand`. Refer to README for details, and the example project has been updated to use it as well. Be sure to put an `ExpandableNotifier` around `ScrollOnExpand` and `Expandable`.
