### ISSUE TITLE
problem to use RectGetter on this library

### ISSUE THREAD

**Issue by MahdiPishguy** [aryzhov/flutter-expandable#17]
when i try to use `RectGetter` widget expanding this library doesn't work correctly and after clicking of expanding icon that collapse automatically

**Comment by aryzhov** [comment]
Please provide an isolated example that reproduces the problem. Determine if the issue is with not with `RectGetter` but with `Expandable` and provide an example that demonstrates the problem without `RectGetter`. The reason why I am asking for this is because debugging other packages is out of the scope of this project. If you claim there's a bug, please make an effort to isolate the issue and provide a minimally reproducible example.

**Comment by MahdiPishguy** [comment]
@aryzhov i'm not sure how can i solved that and i don't have problem now
