### ISSUE TITLE
Tap on body of ExpandablePanel does not expand the widget when it is collapsed.

### ISSUE THREAD

**Issue by bambinoua** [aryzhov/flutter-expandable#41]
Tap on body of ExpandablePanel **does not expand** the widget when it is collapsed. Tap on body of ExpandablePanel **collapse** the widget when it is expanded. In version 3.0.1 _tap on body behavour_ was the same as _tap on icon behavour_. Is it possible to fix this?

**Comment by aryzhov** [comment]
I will take a look, thank you.

**Comment by Viper-Bit** [comment]
@aryzhov i think it comes from line 458
```dart
        return builder(context, collapsed, buildBody(expanded));
```
and line 461
```dart
          collapsed: collapsed,
```
maybe u missed buildBody for collapsed object, i can make a pull if u will
[https://github.com/aryzhov/flutter-expandable/blob/6d3349911da304013dba9ed84b0aa7f946950f77/lib/expandable.dart#L458](url)
[https://github.com/aryzhov/flutter-expandable/blob/6d3349911da304013dba9ed84b0aa7f946950f77/lib/expandable.dart#L461](url)

**Comment by aryzhov** [comment]
The current behavior is by design. The parameter `tapBodyToCollapse` works only for collapsing, not for expanding. ExpandablePanel has an icon that is supposed to be used for expansion. Optionally, you may use `tapHeaderToExpand` to extend the expansion trigger to the header. Extending this to the body would not yield better usability as the user would not know that clicking on the body would expand it. In addition, if your collapsed body is long enough, it might impact scrolling where the user accidentally expands the body by clicking on it.

The reason `tapBodyOnCollapse` exists is for cases when the expanded body occupies the entire screen and there's no desire to add a button that collapses it. 

If you still wish to implement this behavior, simply wrap your expanded body into `ExpandableButton`.

**Comment by aryzhov** [comment]
I added this feature to version 4.1.0 that has been released. You can specify `tabBodyToExpand: true` in the theme.
