### ISSUE TITLE
Collapses once StreamBuilder is triggered

### ISSUE THREAD

**Issue by GideonWislang** [aryzhov/flutter-expandable#7]
How do I stop it from collapsing if it is open when the state changes

**Comment by aryzhov** [comment]
There can be a couple of reasons for your issue: 
* You are using an older version of the package. Make sure you are using version >= 2.1.0, because that's where there was a fix added for state.
* If you are dealing with lists, you need to specify a key for every one of your top-level list item widgets in order to correctly preserve their state between rebuilds. Here's a good video that explains this: [When to use keys](https://www.youtube.com/watch?v=kn0EOS-ZiIc).

In order to facilitate the use of keys, I added the optional `key` parameter to `ExpandablePanel` and `Expandable` and released version 2.1.1. The key will help preserve the expanded state if one of these widgets is the top-level list item widget. If not, you need to provide the key to the top-level widget instead.

**Comment by Zerocchi** [comment]
I'm using `Expandable` widget to create a custom expandable panel. But when I put the `TextFormField` widget inside the `Expandable` widget and focus in it, the widgets get rebuilt and my panel collapsed afterwards. By referring to this issue, how do I make use of key to ensure the panel won't collapse when the state changes (i.e. focus on `TextFormField`)?

**Comment by aryzhov** [comment]
@Zerocchi I modified the example app to include a TextFormField as the `expanded` widget and I don't see any issues. The panel keeps expanded after the field gets focus.

To answer your question "How do I make use of key to ensure the panel won't collapse when the state changes?": The key should not be necessary, unless you are dealing with a list of `ExpandablePanel` widgets. The `Expandable` widget is stateless, its state comes from `ExpandableController`. Perhaps your issue is that you somehow reinitialize `ExpandableController` or change its value when you put focus on the field, but it's just a guess since I can't see your code. For further understanding I'd like to refer you to the same video [When to use keys](https://www.youtube.com/watch?v=kn0EOS-ZiIc) that I mentioned in my previous answer.

**Comment by Zerocchi** [comment]
> Perhaps your issue is that you somehow reinitialize `ExpandableController` or change its value when you put focus on the field, but it's just a guess since I can't see your code.

Your guess is right, and thank you for quick and very detailed response as well as the video!
